models:
  unstable-revolution-f2k-4b:
    enabled: false
    name: "Unstable Revolution FLUX.2 Klein 4B"
    description: " Unstable Revolution FLUX.2 [klein] unifies generation and editing in a single compact architecture"
    capabilities: ["text-to-image", "imgedit"]
    supports_negative_prompt: false
    command: "./bin/sd-server"
    args:
      - "--diffusion-model"
      - "./models/unstableRevolutionF2K_AlphaF2K4B.safetensors"
      - "--vae"
      - "./models/vae/flux2_klein_vae.safetensors"
      - "--llm"
      - "./models/qwen3/qwen_3_4b.safetensors"
      - "-v"
      - "--steps"
      - "6"
    mode: "on_demand"
    exec_mode: "auto"
    # Port is dynamically allocated (40000-49000 range)
    model_type: "imgedit"
    default_size: "1024x1024"
    startup_timeout: 120000
    generation_params:
      cfg_scale: 1.0
      sample_steps: 4
      sampling_method: "euler"

  unstable-revolution-f2k-9b:
    enabled: false
    name: "Unstable Revolution FLUX.2 Klein 9B"
    description: " Unstable Revolution FLUX.2 [klein] unifies generation and editing in a single compact architecture"
    capabilities: ["text-to-image", "imgedit"]
    supports_negative_prompt: false
    command: "./bin/sd-server"
    args:
      - "--diffusion-model"
      - "./models/unstableRevolutionF2K_AlphaF2K4B.safetensors"
      - "--vae"
      - "./models/vae/flux2_klein_vae.safetensors"
      - "--llm"
      - "./models/qwen3/qwen_3_8b.safetensors"
      - "-v"
      - "--steps"
      - "6"
    mode: "on_demand"
    exec_mode: "auto"
    # Port is dynamically allocated (40000-49000 range)
    model_type: "imgedit"
    default_size: "1024x1024"
    startup_timeout: 120000
    generation_params:
      cfg_scale: 1.0
      sample_steps: 4
      sampling_method: "euler"
